apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: origin-hello-openshift
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: origin-hello-openshift
    app.kubernetes.io/part-of: test-samples
  name: origin-hello-openshift
  namespace: mdsaud
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: origin-hello-openshift
    weight: 100
status: {}
